### ISSUE TITLE
Encryption not working on Linux

### ISSUE THREAD

**Issue by AlbertCloete** [alangrainger/epic-journal#2]
I can enter any password and it still opens my journal database fine. I'm also able to read the unecrypted data using an SQL explorer in the database file.

**Comment by alangrainger** [comment]
Unfortunately this is expected behaviour. I am unable to get https://github.com/fritx/unix-sqlcipher/ to work correctly.

I have opened an issue with the dev, but so far it's not resolved.

If you are a developer, please see if you can do any better! My thread is here: fritx/unix-sqlcipher#4

Thanks :)

**Comment by greenhatman** [comment]
How are you envisaging the mobile app to work? Will there be a server component for syncing? In which case there might be other solutions to try server side for encrypting data. Maybe something like Vault.

**Comment by alangrainger** [comment]
I was thinking simply syncing the .epic file with your preferred cloud storage option - Dropbox, Google Drive, etc, and just opening from there.

**Comment by neoxxx85** [comment]
Up, anyone have find a solution for enable encryption on OSX & WIN electron projects ?

**Comment by alangrainger** [comment]
Will be fixed in v2 with "@journeyapps/sqlcipher"
