### ISSUE TITLE
Feature request: spell checking

### ISSUE THREAD

**Issue by greenhatman** [alangrainger/epic-journal#3]

**Comment by alangrainger** [comment]
Hi @greenhatman 
I specifically didn't include spell checking.

2 reasons. The first is that I didn't find any packages that actually worked consistently with Electron, so that was number one. 

But the second reason is that a paper journal doesn't have spellcheck. I quite like the ability to smash out some long morning pages without seeing squiggly lines everywhere. Epic is not intended to be a word processor so for me I think it is great without it.

Hope that's not too bad!
